CREATE TABLE role
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE user_role
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_type   VARCHAR(20),
    email       VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    nom         VARCHAR(50)                             NOT NULL,
    prenom      VARCHAR(50)                             NOT NULL,
    telephone   VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    age         INTEGER,
    profession  VARCHAR(100),
    preferences VARCHAR(255),
    adresse     VARCHAR(100),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE role
    ADD CONSTRAINT uc_role_nom UNIQUE (nom);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_role FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_user FOREIGN KEY (user_id) REFERENCES users (id);