-- Table Contract
CREATE TABLE contract
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id       BIGINT                                  NOT NULL,
    tenant_id         BIGINT                                  NOT NULL,
    proprietaire_id   BIGINT                                  NOT NULL,
    date_debut        DATE                                    NOT NULL,
    date_fin          DATE                                    NOT NULL,
    loyer_mensuel     DECIMAL(10, 2)                         NOT NULL,
    depot_garantie    DECIMAL(10, 2)                         NOT NULL,
    statut            VARCHAR(20)                            NOT NULL,
    conditions        TEXT,
    created_at        TIMESTAMP WITHOUT TIME ZONE            NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE            NOT NULL,
    CONSTRAINT pk_contract PRIMARY KEY (id)
);

-- Table Tenant (Locataire)
CREATE TABLE tenant
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    nom               VARCHAR(100)                            NOT NULL,
    prenom            VARCHAR(100)                            NOT NULL,
    email             VARCHAR(255)                            NOT NULL,
    telephone         VARCHAR(20),
    date_naissance    DATE,
    profession        VARCHAR(100),
    revenu_mensuel    DECIMAL(10, 2),
    document_identite VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE            NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE            NOT NULL,
    CONSTRAINT pk_tenant PRIMARY KEY (id)
);

-- Table Rent (Loyer)
CREATE TABLE rent
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contract_id     BIGINT                                  NOT NULL,
    mois            INTEGER                                 NOT NULL,
    annee           INTEGER                                 NOT NULL,
    montant         DECIMAL(10, 2)                         NOT NULL,
    date_echeance   DATE                                    NOT NULL,
    date_paiement   DATE,
    statut_paiement VARCHAR(20)                            NOT NULL,
    mode_paiement   VARCHAR(50),
    reference       VARCHAR(100),
    created_at      TIMESTAMP WITHOUT TIME ZONE            NOT NULL,
    CONSTRAINT pk_rent PRIMARY KEY (id)
);

-- Table Deposit (Caution/Garantie)
CREATE TABLE deposit
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contract_id      BIGINT                                  NOT NULL,
    montant          DECIMAL(10, 2)                         NOT NULL,
    date_versement   DATE                                    NOT NULL,
    date_restitution DATE,
    montant_retenu   DECIMAL(10, 2),
    statut           VARCHAR(20)                            NOT NULL,
    motif_retenue    TEXT,
    created_at       TIMESTAMP WITHOUT TIME ZONE            NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE            NOT NULL,
    CONSTRAINT pk_deposit PRIMARY KEY (id)
);

-- Constraints
ALTER TABLE contract
    ADD CONSTRAINT ck_contract_statut
        CHECK (statut IN ('ACTIF', 'TERMINE', 'RESILIE', 'EN_ATTENTE'));

ALTER TABLE rent
    ADD CONSTRAINT ck_rent_statut_paiement
        CHECK (statut_paiement IN ('EN_ATTENTE', 'PAYE', 'EN_RETARD', 'ANNULE'));

ALTER TABLE rent
    ADD CONSTRAINT ck_rent_mois
        CHECK (mois >= 1 AND mois <= 12);

ALTER TABLE deposit
    ADD CONSTRAINT ck_deposit_statut
        CHECK (statut IN ('VERSE', 'RESTITUE', 'RETENU_PARTIELLEMENT'));

-- Foreign Keys
ALTER TABLE rent
    ADD CONSTRAINT fk_rent_on_contract
        FOREIGN KEY (contract_id) REFERENCES contract (id) ON DELETE CASCADE;

ALTER TABLE deposit
    ADD CONSTRAINT fk_deposit_on_contract
        FOREIGN KEY (contract_id) REFERENCES contract (id) ON DELETE CASCADE;

-- Indexes for performance
CREATE INDEX idx_contract_property_id ON contract(property_id);
CREATE INDEX idx_contract_tenant_id ON contract(tenant_id);
CREATE INDEX idx_contract_proprietaire_id ON contract(proprietaire_id);
CREATE INDEX idx_contract_statut ON contract(statut);
CREATE INDEX idx_tenant_user_id ON tenant(user_id);
CREATE INDEX idx_tenant_email ON tenant(email);
CREATE INDEX idx_rent_contract_id ON rent(contract_id);
CREATE INDEX idx_rent_statut_paiement ON rent(statut_paiement);
CREATE INDEX idx_deposit_contract_id ON deposit(contract_id);